ruby '2.3.1'
source 'https://rubygems.org'

gem 'scraperwiki', git: 'https://github.com/openaustralia/scraperwiki-ruby.git', branch: 'morph_defaults'
gem 'mechanize'
gem 'pry'
gem 'geokit'
gem 'activesupport'
gem 'reverse_markdown'
gem 'dotenv'
